### ISSUE TITLE
Use Quarto to output PDF / HTML

### ISSUE THREAD

**Issue by JohnShiuMK** [UBC-MDS/fixml#108]

**Comment by tonyshumlh** [comment]
Hi @SoloSynth1 
I have tried to create a new conda env with only `r-quarto` specified in `environment.yml`
However, a bunch of r packages were also installed as the dependency (screenshot attached, not exhaustive)
<img width="696" alt="Screenshot 2024-06-07 at 6 18 30 PM" src="https://github.com/UBC-MDS/test-creation/assets/38127942/ec641641-946a-4149-9402-415052d611b1">

If I understand the question correctly, it is that `quarto` version in `pip` and `poetry` is too old (0.1.0) (Is it?)
<img width="306" alt="Screenshot 2024-06-07 at 6 46 44 PM" src="https://github.com/UBC-MDS/test-creation/assets/38127942/27798d09-7363-4634-891e-78fc4a6135ea">

Since `r-quarto` cannot be included in `poetry` and also relies on conda, shall we include `quarto` instead of `r-quarto` in `environment.yml`? 
<img width="522" alt="Screenshot 2024-06-07 at 6 39 53 PM" src="https://github.com/UBC-MDS/test-creation/assets/38127942/0cb09eeb-11c2-43cf-9ce6-af172d1d5522">

**Comment by SoloSynth1** [comment]
After discussing with Simon and Tiffany it has been deemed not necessary to incorporate the Quarto workflow. Closing this issue as this feature won't be implemented for now.
